config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :purchase_details

  resources :data_inputs

   root 'data_inputs#new'

end

app/models/data_input.rb
class DataInput < ActiveRecord::Base
	has_attached_file :tab
validates :tab, presence: true ,format: {  with: %r{\.(tab|tsv)\z}i , message: "Please enter .tab file only"}
end

app/models/purchase_detail.rb
class PurchaseDetail < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/data_inputs_controller.rb
class DataInputsController < ApplicationController
  before_action :set_data_input, only: [:show, :edit, :update, :destroy]

  # GET /data_inputs
  # GET /data_inputs.json
  def index
    @data_inputs = DataInput.all
  end

  # GET /data_inputs/1
  # GET /data_inputs/1.json
  def show
  end

  # GET /data_inputs/new
  def new
    @data_input = DataInput.new
  end

  # GET /data_inputs/1/edit
  def edit
  end

  # POST /data_inputs
  # POST /data_inputs.json
  def create
    @data_input = DataInput.new(data_input_params)
     
    respond_to do |format|
      if @data_input.save
	  file = @data_input.tab.url
	  File.readlines("#{Rails.root}"+'/public' + file ).drop(1).map do |line|
		  purchaser_name,item_description,item_price,purchase_count,merchant_address,merchant_name  = line.split("\t") 
		  purchase = PurchaseDetail.new
		  purchase.purchaser_name = purchaser_name
		  purchase.item_description = item_description
		  purchase.item_price = item_price
		  purchase.purchase_count = purchase_count
		  purchase.merchant_address = merchant_address
		  purchase.merchant_name = merchant_name
		  purchase.save  
	end
        format.html { redirect_to :controller=>"purchase_details" }
        format.json { render :show, status: :created, location: @data_input }
      else
        format.html { render :new }
        format.json { render json: @data_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_inputs/1
  # PATCH/PUT /data_inputs/1.json
  def update
    respond_to do |format|
      if @data_input.update(data_input_params)
        format.html { redirect_to @data_input, notice: 'Data input was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_input }
      else
        format.html { render :edit }
        format.json { render json: @data_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_inputs/1
  # DELETE /data_inputs/1.json
  def destroy
    @data_input.destroy
    respond_to do |format|
      format.html { redirect_to data_inputs_url, notice: 'Data input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_input
      @data_input = DataInput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_input_params
      params.require(:data_input).permit(:name,:tab)
    end
end

app/controllers/purchase_details_controller.rb
class PurchaseDetailsController < ApplicationController
  before_action :set_purchase_detail, only: [:show, :edit, :update, :destroy]

  # GET /purchase_details
  # GET /purchase_details.json
  def index
    @purchase_details = PurchaseDetail.all
    @total_amount = @purchase_details.to_a.sum { |item| item.item_price }
  end

  # GET /purchase_details/1
  # GET /purchase_details/1.json
  def show
  end

  # GET /purchase_details/new
  def new
    @purchase_detail = PurchaseDetail.new
  end

  # GET /purchase_details/1/edit
  def edit
  end

  # POST /purchase_details
  # POST /purchase_details.json
  def create
    @purchase_detail = PurchaseDetail.new(purchase_detail_params)

    respond_to do |format|
      if @purchase_detail.save
        format.html { redirect_to @purchase_detail, notice: 'Purchase detail was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_detail }
      else
        format.html { render :new }
        format.json { render json: @purchase_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_details/1
  # PATCH/PUT /purchase_details/1.json
  def update
    respond_to do |format|
      if @purchase_detail.update(purchase_detail_params)
        format.html { redirect_to @purchase_detail, notice: 'Purchase detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_detail }
      else
        format.html { render :edit }
        format.json { render json: @purchase_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_details/1
  # DELETE /purchase_details/1.json
  def destroy
    @purchase_detail.destroy
    respond_to do |format|
      format.html { redirect_to purchase_details_url, notice: 'Purchase detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_detail
      @purchase_detail = PurchaseDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_detail_params
      params.require(:purchase_detail).permit(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_inputs_helper.rb
module DataInputsHelper
end

app/helpers/purchase_details_helper.rb
module PurchaseDetailsHelper
end

app/views/data_inputs/_form.html.erb
<%= form_for(@data_input) do |f| %>
  <% if @data_input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_input.errors.count, "error") %> prohibited this data_input from being saved:</h2>

      <ul>
      <% @data_input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
  <%= f.file_field :tab %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_inputs/edit.html.erb
<h1>Editing data_input</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_input %> |
<%= link_to 'Back', data_inputs_path %>

app/views/data_inputs/index.html.erb
<h1>Listing data_inputs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_inputs.each do |data_input| %>
      <tr>
        <td><%= data_input.name %></td>
        <td><%= data_input.tab_file_name %></td>
        <td><%= link_to 'Show', data_input %></td>
        <td><%= link_to 'Edit', edit_data_input_path(data_input) %></td>
        <td><%= link_to 'Destroy', data_input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Data input', new_data_input_path %> | 
<%= link_to 'Purchase Details', purchase_details_path %>

app/views/data_inputs/new.html.erb
<h1>New data_input</h1>

<%= render 'form' %>

<%= link_to 'Back', data_inputs_path %>

app/views/data_inputs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @data_input.name %>
</p>

<%= link_to 'Edit', edit_data_input_path(@data_input) %> |
<%= link_to 'Back', data_inputs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataEngineering</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/purchase_details/_form.html.erb
<%= form_for(@purchase_detail) do |f| %>
  <% if @purchase_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_detail.errors.count, "error") %> prohibited this purchase_detail from being saved:</h2>

      <ul>
      <% @purchase_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchaser_name %><br>
    <%= f.text_field :purchaser_name %>
  </div>
  <div class="field">
    <%= f.label :item_description %><br>
    <%= f.text_area :item_description %>
  </div>
  <div class="field">
    <%= f.label :item_price %><br>
    <%= f.text_field :item_price %>
  </div>
  <div class="field">
    <%= f.label :purchase_count %><br>
    <%= f.number_field :purchase_count %>
  </div>
  <div class="field">
    <%= f.label :merchant_address %><br>
    <%= f.text_area :merchant_address %>
  </div>
  <div class="field">
    <%= f.label :merchant_name %><br>
    <%= f.text_field :merchant_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchase_details/edit.html.erb
<h1>Editing purchase_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase_detail %> |
<%= link_to 'Back', purchase_details_path %>

app/views/purchase_details/index.html.erb
<h1>Listing purchase_details</h1>

<table border="1">
  <thead>
    <tr>
      <th>Purchaser name</th>
      <th>Item description</th>
      <th>Item price</th>
      <th>Purchase count</th>
      <th>Merchant address</th>
      <th>Merchant name</th>
      <th colspan="3">CRUD</th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_details.each do |purchase_detail| %>
      <tr>
        <td><%= purchase_detail.purchaser_name %></td>
        <td><%= purchase_detail.item_description %></td>
        <td><%= purchase_detail.item_price %></td>
        <td><%= purchase_detail.purchase_count %></td>
        <td><%= purchase_detail.merchant_address %></td>
        <td><%= purchase_detail.merchant_name %></td>
        <td><%= link_to 'Show', purchase_detail %></td>
        <td><%= link_to 'Edit', edit_purchase_detail_path(purchase_detail) %></td>
        <td><%= link_to 'Destroy', purchase_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />
<b>Total Amount <%= number_to_currency(@total_amount)%></b>

<br>
<br>

<%= link_to 'New Data input', new_data_input_path %>

app/views/purchase_details/new.html.erb
<h1>New purchase_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', purchase_details_path %>

app/views/purchase_details/show.html.erb
<p>
  <strong>Purchaser name:</strong>
  <%= @purchase_detail.purchaser_name %>
</p>

<p>
  <strong>Item description:</strong>
  <%= @purchase_detail.item_description %>
</p>

<p>
  <strong>Item price:</strong>
  <%= @purchase_detail.item_price %>
</p>

<p>
  <strong>Purchase count:</strong>
  <%= @purchase_detail.purchase_count %>
</p>

<p>
  <strong>Merchant address:</strong>
  <%= @purchase_detail.merchant_address %>
</p>

<p>
  <strong>Merchant name:</strong>
  <%= @purchase_detail.merchant_name %>
</p>

<%= link_to 'Edit', edit_purchase_detail_path(@purchase_detail) %> |
<%= link_to 'Back', purchase_details_path %>